name: demo workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Prnt to console
        run: echo Hello gh actions
      - name: Print a few lines 
        run: | 
          echo first
          echo second
